### DISCUSSION TITLE
Keepalived and IPA-downloader support as plugins?

### DISCUSSION THREAD

**Discussion by dtantsur** [metal3-io/ironic-standalone-operator#74] [General]
Hi folks,

I've been thinking about connecting keepalived support to IrSO (without it, metal3-dev-env won't work). Similarly to IronicDatabase, we could just create a Keepalived resource. Not similarly to IronicDatabase, keepalived has to be deployed into the same Deployment as Ironic (but not on HA, I guess?).

On top of that, I'm thinking how to enable downstream modifications. For example, OpenShift does not use Keepalived, it injects something else into the pod.

**Comment by dtantsur** [comment]
Option 1: hardcode Keepalived support, let OpenShift fork the project. As an OpenShift developer, I'd hate this.

**Comment by dtantsur** [comment]
Option 2: some sort of CR-level plugins? Imagine, I create an Ironic this way:

```yaml
---
apiVersion: metal3.io/v1alpha1
kind: Keepalived
metadata:
  name: ironic-sample
spec: {}
---
apiVersion: metal3.io/v1alpha1
kind: Ironic
metadata:
  name: ironic-sample
spec:
  networking:
    ipAddress: 172.0.2.2
    ipManagerRef:
      apiGroup: metal3.io/v1alpha1
      kind: Keepalived
      name: ironic-sample
```

Then I expect the Keepalived controller to... modify the Deployment? Somehow in a way that the Ironic controller don't override?

This is not a well thought solution, but I'd be curious to hear feedback.
