### ISSUE TITLE
Bad error reporting when the API secret or database is not found

### ISSUE THREAD

**Issue by dtantsur** [metal3-io/ironic-standalone-operator#105]
In this case, the status will get stuck in

```yaml
  status:                                                                                                                                                                                     
    conditions:                                                                                                                                                                               
    - lastTransitionTime: "2024-12-30T11:36:18Z"                                                                                                                                              
      message: new version requested                                                                                                                                                          
      observedGeneration: 1
      reason: DeploymentInProgress
      status: "False"
      type: Ready 
```

with no indication what went wrong except for the manager logs. What we probably should do is to report the exact error via this condition. Something like

```yaml
  status:                                                                                                                                                                                     
    conditions:                                                                                                                                                                               
    - lastTransitionTime: "2024-12-30T11:36:18Z"                                                                                                                                              
      message: cannot read the API credentials secret                                                                                                                                                         
      observedGeneration: 1
      reason: DeploymentFailed
      status: "False"
      type: Ready 
```

Generally, error conditions in the operator need some love. Testing welcome.

/kind bug
/help
