### ISSUE TITLE
Reconsider having explicit support for deploying MariaDB

### ISSUE THREAD

**Issue by dtantsur** [metal3-io/ironic-standalone-operator#142]
There is presumably no shortage of ways to deploy MariaDB that are better supported than mariadb-image. [The official documentation](https://mariadb.com/kb/en/kubernetes-operators-for-mariadb/) refers to [mariadb-operator](https://github.com/mariadb-operator/mariadb-operator). By relying on an external operator we can get HA and upgrades for free.

The proposal here is to deprecate and remove `IronicDatabase` CR, mariadb-image repository and start accepting a link to an externally managed MariaDB, e.g. like this:

```yaml
spec:
  database:
    serviceName: mydb-primary
    name: myironic
    credentialsName: secret-with-credentials
    tlsName: secret-with-tls-cert-or-ca
```

Open questions:
- Any reasons to keep mariadb-image?
- Are we okay with referring to a service?
- Are we okay with not supporting databases from other namespaces?
- Do we need to support IP:PORT for databases that are not deployed in Kubernetes?
- Anything else we need there?

/kind feature
/triage accepted
