### ISSUE TITLE
RFE: support for passing extra configuration

### ISSUE THREAD

**Issue by dtantsur** [metal3-io/ironic-standalone-operator#87]
Realistically, some users want to provide additional ironic.conf options. The configuration engine allows to set any option via environment variable, and we even document it in the ironic-image README.

The API should look something like this:
```yaml
spec:
  extraConfig:
  - group: pxe
    name: boot_retry_timeout
    value: "1200"
  - group: conductor
    name: inspect_timeout
    value: "1800"
```

The environment variable name is formed as follows:
1. `OS_` prefix
2. The name of the group in upper case (dashes replaced by underscores), the default group is `DEFAULT`
3. Double underscore `__`
4. The name of the option in upper case (dashes replaced by underscores)

In the example above, we should set two variables:
- `OS_PXE__BOOT_RETRY_TIMEOUT=1200`
- `OS_CONDUCTOR__INSPECT_TIMEOUT=1800`

/kind feature
/help
